from pymatgen.core import Structure
from pymatgen.analysis.diffraction.xrd import XRDCalculator
#from .filereader import load_image
import fabio
import os
import sys
import numpy as np
from .id11data import ID11Data

def build_calibration_data_from_cif(
    cif_file,
    wavelength,
    n_peaks=10,
    q_range=(0.0, 5.0),
):
    """
    Generate diffraction peaks from a CIF structure file within a q range.

    Parameters
    ----------
    cif_file : str
        Path to the CIF structure file.
    wavelength : float
        Wavelength in Å.
    n_peaks : int, optional
        Maximum number of peaks to return.
    q_range : tuple(float, float), optional
        q range (Å⁻¹).

    Returns
    -------
    peaks : list of dict
        Each element contains:
            - hkl
            - d
            - q
            - two_theta
            - intensity
    """

    structure = Structure.from_file(cif_file)

    xrd = XRDCalculator(wavelength=wavelength)

    qmin, qmax = q_range

    # Conversion q -> 2theta
    def q_to_two_theta(q):
        x = q * wavelength / (4 * np.pi)
        if x > 1:
            raise ValueError(
                f"q={q:.3f} Å⁻¹ is not accessible with λ={wavelength:.5f} Å."
            )
        return np.degrees(2 * np.arcsin(x))

    two_theta_range = (
        q_to_two_theta(qmin),
        q_to_two_theta(qmax),
    )

    pattern = xrd.get_pattern(
        structure,
        two_theta_range=two_theta_range,
    )

    print(
        f"Found {len(pattern.x)} peaks in q range {q_range} Å⁻¹ "
        f"(2θ={two_theta_range[0]:.2f}–{two_theta_range[1]:.2f}°)."
    )

    peaks = []
    for i in range(min(n_peaks, len(pattern.x))):

        two_theta = pattern.x[i]
        theta = np.radians(two_theta / 2)
        q = 4 * np.pi * np.sin(theta) / wavelength

        peaks.append(
            {
                "hkl": pattern.hkls[i][0]["hkl"],
                "d": pattern.d_hkls[i],
                "q": q,
                "two_theta": two_theta,
                "intensity": pattern.y[i],
            }
        )

    with open("./distances.txt", "w") as f:
        for p in peaks:
            f.write(f"{p['d']}\n")

    return peaks


def perform_geometric_calibration(
        cif_file: str,
        image_file: str,
        wavelength: float = None):
    """
    Perform geometric calibration of electron diffraction data using pyFAI-calib2.

    Exports the image as a temporary EDF file, optionally applies MTF
    deconvolution, computes calibrant d-spacings from the CIF, prints
    the instrument settings to enter in pyFAI-calib2, and launches the
    calibration GUI.

    Parameters
    ----------
    cif_file : str
        Path to the CIF structure file of the calibrant.
    image_file : str
        Path to the DM4 image file of the calibrant diffraction pattern.
    mtf_file : str, optional
        Path to the MTF file. If provided, Wiener deconvolution is applied
        to the image before calibration.
    """
    
    # load data and metadata
    eiger = ID11Data(image_file)
    #detector_info, raw_image = load_image(image_file)
    
    if eiger.data.ndim == 3:
        eiger.data = np.mean(eiger.data, axis=0)  # average frames if multiple frames are present:

    # Define output EDF file name
    edffile = os.path.splitext(image_file)[0] + '.edf'

    # Create EDF image and save
    edf_image = fabio.edfimage.EdfImage(data=eiger.data, header=eiger.detector_info)
    edf_image.write(edffile)

    # Create distance files for use in pyFAI-calib2
    peaks = build_calibration_data_from_cif(
        cif_file,
        wavelength=eiger.detector_info['wavelength'] if wavelength is None else wavelength,
        n_peaks=10)
    
    print("=" * 70)
    print('EXPERIMENT SETTINGS TO INPUT IN PYFAI-CALIB2:')
    print('='*70)
    print(f'Camera description={eiger.detector_info["description"]}')
    print(f'pixel_size_x={eiger.detector_info["pixel_size"]}X{eiger.detector_info["pixel_size"]}')  # in µmeters
    print(f'image dimension={eiger.detector_info["image_width"]}X{eiger.detector_info["image_height"]}') # in pixels 
    #print(f'Electron wavelength={eiger.detector_info["wavelength"]} Å')

    print('=' * 70 )
    print('Launching pyFAI-calib2')
    os.system(f'"{sys.executable}" -m pyFAI.app.calib2 -c ./distances.txt {edffile}')
    
    # Clean up distance file and edf file
    os.remove(edffile)
    os.remove('./distances.txt')


def get_calibration_parameters(poni_file: str):
    """
    Extract calibration parameters from a PONI file generated by pyFAI-calib2.

    Parameters
    ----------
    poni_file : str
        Path to the PONI file produced after calibration.

    Returns
    -------
    calibration_params : dict
        Dictionary containing the following keys (when present in the file):

        - ``'distance'``: sample-to-detector distance (m)
        - ``'poni1'``, ``'poni2'``: point of normal incidence coordinates (m)
        - ``'rot1'``, ``'rot2'``, ``'rot3'``: detector rotation angles (rad)
        - ``'wavelength'``: wavelength (m)
        - ``'pixel1'``, ``'pixel2'``: pixel sizes (m)
        - ``'max_shape'``: detector shape in pixels
    """
    import json
    calibration_params = {}
    if not os.path.exists(poni_file):
        raise FileNotFoundError(f"Fichier PONI non trouvé: {poni_file}")

    with open(poni_file, 'r') as f:
        lines = f.readlines()

    for line in lines:
        if line.startswith('Distance:'):
            calibration_params['distance'] = float(line.split(':')[1].strip())
        elif line.startswith('Poni1:'):
            calibration_params['poni1'] = float(line.split(':')[1].strip())
        elif line.startswith('Poni2:'):
            calibration_params['poni2'] = float(line.split(':')[1].strip())
        elif line.startswith('Rot1:'):
            calibration_params['rot1'] = float(line.split(':')[1].strip())
        elif line.startswith('Rot2:'):
            calibration_params['rot2'] = float(line.split(':')[1].strip())
        elif line.startswith('Rot3:'):
            calibration_params['rot3'] = float(line.split(':')[1].strip())
        elif line.startswith('Wavelength:'):
            calibration_params['wavelength'] = float(line.split(':')[1].strip())
        elif line.startswith('Detector_config:'):
            config_str = line.split(':', 1)[1].strip()
            config = json.loads(config_str)
            calibration_params['pixel1'] = config.get('pixel1', None)
            calibration_params['pixel2'] = config.get('pixel2', None)
            calibration_params['max_shape'] = config.get('max_shape', None)

    return calibration_params

